id: P001725
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG18631
  title: སྐད་ཡིག་གི་འབོད་སྒྲ།
  author: ''
  volumes:
    b51e26a6ecc44da1bc7340f421795e1d:
      image_group_id: I1KG20660
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
